version: 1.2
workflows:
  - name: foobar
    subclass: wdl
    primaryDescriptorPath: /Dockstore.wdl
    authors:
      - name: Denis Yuen
        orcid: 0000-0002-6130-1021
      - name: Gregory Hogue
        email: gfjhogue@gmail.com
        role: Software Developer
        affiliation: OICR
      - name: Just Name
      - orcid: 0000-0000-0000-0000
      - orcid: 0000-0001-7641-7724
        
