version: 1.2
workflows:
  - name: foobar
    subclass: wdl
    primaryDescriptorPath: /Dockstore.wdl
    authors:
      - name: Denis Yuen
        orcid: 0000-0002-6130-1021
      - name: Gregory Hogue
        email: gfjhogue@gmail.com
        role: Software Developer
        affiliation: OICR
      - name: Just Name
      - orcid: 0000-0000-0000-0000
      - name: Kathy
        email: test@gmail.com
        role: Software Developer
        affiliation: Ontario Institute for Cancer Research
      - name: This is a very very very very very long name
        email: this-is-a-very-very-very-very-very-long-email@gmail.com
        role: This is a very very very very very long role
        affiliation: This is a very very very very very long affiiliation
      - name: This is a very very very very very very very very very very long name
        email: this-is-a-very-very-very-very-very-very-very-very-very-very-long-email@gmail.com
        role: This is a very very very very very very very very very very long role
        affiliation: This is a very very very very very very very very very very long affiiliation
  - name: foobar2
    subclass: cwl
    primaryDescriptorPath: /Dockstore.cwl
    authors:
      - name: Potato Author
        email: potato.author@gmail.com
      - orcid: 0000-1234-5678-0000
  - name: foobar3
    subclass: nfl
    primaryDescriptorPath: /nextflow.config
    authors:
      - name: Tomato Author
        role: Test User
      - orcid: 1111-1111-1111-1111
