version: 1.2
workflows:
  - name: foobar
    subclass: wdl
    primaryDescriptorPath: /Dockstore.wdl
    authors:
    - orcid: 0000-0001-7641-7724
    - name: Test Author
      role: Test Role
      email: foobar@gmail.com
      affiliation: Test Organization
  - name: foobar2
    subclass: cwl
    primaryDescriptorPath: /Dockstore.cwl
    authors:
      - name: Potato Author
        email: potato.author@gmail.com
      - name: Normal Author
        email: normal.author@gmail.com
        role: Normal Author Role
        affiliation: Normal Author Affiliation
  - name: foobar3
    subclass: nfl
    primaryDescriptorPath: /nextflow.config
    authors:
      - name: Tomato Author
        role: Test User
