version: 1.2
workflows:
  - name: foobar
    subclass: wdl
    primaryDescriptorPath: /Dockstore.wdl
    authors:
    - orcid: 0000-0001-7641-7724 
    - orcid: 0000-0001-8365-0487 
    - orcid: 0000-0002-1928-4854 
    - orcid: 0000-0002-6709-3948 
  - name: foobar2
    subclass: cwl
    primaryDescriptorPath: /Dockstore.cwl
    authors:
      - name: Potato Author
        email: potato.author@gmail.com
      - name: Normal Author
        email: normal.author@gmail.com
        role: Normal Author Role
        affiliation: Normal Author Affiliation
  - name: foobar3
    subclass: nfl
    primaryDescriptorPath: /nextflow.config
    authors:
      - name: Tomato Author
        role: Test User
